### PR TITLE
Merge Trunk v1.5.2

### PR DESCRIPTION
**Pull request by juyeongkim**

### CODE REVIEW

**Comment by ldash** [comment]
Also, what are the 6 or so instances of commented out code bits `#broken`?
What's broken there and can it be fixed?

Finally, there's a `takes too long` commented out piece - how long is too long?
Can we still include this in the code base, but not in the main automated tests section, may be, but somewhere else, where we can kick off these tests overnight occasionally?

**Comment by ehfhcrc** [comment]
@ldash the tests are fixable and I have worked on some of them in a separate local branch, but I didn't want to hold back the merge process previously (all tests must be passing for Travis / bioconductor to accept).  In terms of the # takes too long comment ... I am not sure as I never let it run to conclusion.  I could do that and let you know.

**Comment by ldash** [comment]
@ehfhcrc sure, kick off the "long" test and see, how long it takes.

Let us try not to have commented out code with "broken", "to do", or "wip" tags in the public facing "release" versions, ok? Which also means that it shouldn't be part of the `trunk` branch, right? So it's either in the uncommited working copy or in a feature branch. What do you guys think of that?

And what about my original "review" comment? Can those tests be brought back or did I not notice them somewhere? They don't have to be in the current `dev`, though.

Can all of the non-working, not implemented functionality be moved from the `trunk` to a feature branch then?

**Comment by ehfhcrc** [comment]
re: `Test_EM`, it looks like the two components are no longer there.  I believe I took out the commented-out lines because they were not in use.  Regarding the `is.na` test, I'm not sure why that is out.  I'm currently running R CMD Check on a local branch that has many of the tests fixed and the broken ones removed.  I can push that up to RGLab and we could do a pull request for that one (will be called `fb_moretests`) into `trunk` prior to going to dev so that trunk has only working tests and no commented-out ones?

**Comment by ldash** [comment]
@ehfhcrc that sounds good, let's 1) add the "many" additional tests via a merge to `trunk`, 2) move anything that's `broken` or `wip` from `trunk` to a feature branch, 3) see if we can add the 2 removed tests back: `is.na` one and the `cohort` based one. Then merge to `dev` once again.

**Pull request merged**
