### PR TITLE
Fb pgrp ... finally

### PR DESCRIPTION
**Pull request by ehfhcrc**

### CODE REVIEW

**Comment by ldash** [comment]
So I'm not convinced that we need to expose participant groups other than the current user's ... (We don't do that in the UI). Let's follow this up on Friday.

**Comment by juyeongkim** [comment]
This PR is going to merge into `dev`, not `trunk`...

**Comment by ehfhcrc** [comment]
Thanks for point that out. switched.

**Comment by ehfhcrc** [comment]
So, in response to your first questions and concerns about access via ApiKey and using the first user for the given domain, I have addressed these with the `.validateUser()` method.  It ensures that we know who the `user` is based either on the ApiKey, if present, or finding the first netrc user for the given domain.  I'm not sure why other methods don't do this, but you asked me to do it, so that's what I did.  Perhaps you are being thrown off by the name? I am not so much validating the user I guess, as ensuring I am using the correct username when deciding which participant groups should be shown to the user.

**Comment by ehfhcrc** [comment]
Ok leo, I have updated both of the functions.  The listParticipantGroups() is faster now - I will look into combining two of the remaining queries to see if I can speed it up a little more though.  The getParticipantData() should also be showing original_view columns as appropriate.  I tested with hai and gef.

**Comment by ldash** [comment]
I couldn't figure out, how to append my review or create a new one, so here is my feedback on the latest iteration:

For the `listParticipantGroups` method:

When I wrote
"As much of it as possible needs to be done in SQL itself with as few queries from R as possible!
So either build a parameterized query string and pass it to executeSql() or build a parameterized SQL query and execute it or may be a regular query with a filter parameter"
I meant to not do any JOINS or summaries in R at all, which are slow on their own and there's the querying overhead, but rather all in SQL - you should be able to shed off at least another half of the time if not more that way! In this case it's starting to become negligible, but it's a great practice to think in an "optimized fashion" ;)
You actually sort of started doing that by embedding SQL string 2 into SQL string 3 (embedding SQL string 1 into SQL string 2 this way is trivial, for example).
So in other words, combine all of your logic into just one SQL query with parameter `user` and then shoot off one `executeSql()` call that returns the needed result!
You might've tried that already within this method and the next one and got an error that such and such a query does not exist in a given schema.
In this case, you need to qualify the query in question with a schema name by prepending it: `core.Users`


For the `getParticipantData` method:

Please, update the doc string for `dataType`: to either be `con$available_datasets$Name` or `con$listDatasets('datasets')` (I prefer the 2nd way, since it's documented more)

Please, remove `dt <- tolower(dataType)` as it is redundant since all of your dataType names are lower case already

Same business here: do combine the 2 queries into just one! (Hint: use the schema qualification syntax to query across differing schemas!)

I also just realized that you're calling `listParticipantGroups` within the 2nd method - this warrants caching for the 1st method, right?

And why are you using `labkey.selectRows` in place of your nifty shortcut: `.getLKtbls`?
In fact, I think it's best to use the `getDataset()` method here (passing along the `orig_view` flag) - that data might even be cached already...

Finally, I'm getting the following error:
```
> con$getParticipantData('TB', 'demographics')
Error in processResponse(mydata, header, handle) : 
  HTTP request was unsuccessful. Status code = 500, Error message = Error on line 1: Duplicate column 'age_reported'
> con$getParticipantData(175, 'demographics')
Error in processResponse(mydata, header, handle) : 
  HTTP request was unsuccessful. Status code = 500, Error message = Error on line 1: Duplicate column 'age_reported'
```
Are you not?

Please, check that the method works correctly for all of the available datasets.

Thank you.

**Pull request merged**
