### PR TITLE
hotfixes to handle GroupName and fcs_sample_files errors

### PR DESCRIPTION
**Pull request by ehfhcrc**

### CODE REVIEW

**Comment by ldash** [comment]
Ok, @ehfhcrc I actually did notice hopefully one last little thing that needs to be addressed with the column names of the result.
```
> hai_full <- con$getDataset('hai')
> hai_ptpg <- con$getParticipantData(156, 'hai')
> colnames(hai_full)
[1] "participant_id"            "age_reported"             
[3] "gender"                    "race"                     
[5] "cohort"                    "study_time_collected"     
[7] "study_time_collected_unit" "virus"                    
[9] "value_reported"           
> colnames(hai_ptpg)
[1] "ParticipantId"             "study_time_collected"     
[3] "study_time_collected_unit" "value_reported"           
[5] "virus"                     "age_reported"             
[7] "race"                      "gender"                   
[9] "cohort"                   
> hai_full <- con$getDataset('hai', original_view = T)
> hai_ptpg <- con$getParticipantData(156, 'hai', original_view = T)
> colnames(hai_full)
 [1] "participant_id"            "arm_accession"            
 [3] "biosample_accession"       "expsample_accession"      
 [5] "experiment_accession"      "study_accession"          
 [7] "study_time_collected"      "study_time_collected_unit"
 [9] "virus"                     "value_reported"           
[11] "value_preferred"           "unit_reported"            
[13] "unit_preferred"           
> colnames(hai_ptpg)
 [1] "ParticipantId"             "arm_accession"            
 [3] "biosample_accession"       "expsample_accession"      
 [5] "experiment_accession"      "study_accession"          
 [7] "study_time_collected"      "study_time_collected_unit"
 [9] "value_reported"            "value_preferred"          
[11] "unit_reported"             "unit_preferred"           
[13] "virus"                    
```
So, please, make the order and the names match exactly! (i.e. the infamous "Participant ID"!)
Thank you.

**Comment by ehfhcrc** [comment]
Good catch.

**Comment by ehfhcrc** [comment]
PS - out of curiosity, why does `ParticipantId` have a different format than the rest?

**Comment by ldash** [comment]
You're asking me? I thought, you'd know by now ;)

**Pull request merged**
