### PR TITLE
Fb encapsulation

### PR DESCRIPTION
**Pull request by juyeongkim**
Restructure to public and private methods

Some are renamed to be consistent with the existing naming convention (verb + camelCase), and others are documented for users

### CODE REVIEW

**Comment by ehfhcrc** [comment]
Also looks good to me. Cool to see the pub / private methods happening! I think it will make it a lot cleaner.

**Comment by juyeongkim** [comment]
@ldash @ehfhcrc Renaming is done.

**Comment by juyeongkim** [comment]
@ldash @ehfhcrc `fb_encapsulation` branch is installed and working well on `test`. I modified the modules (DEA, DE, and ImmSig) accordingly, and they are working fine with this branch. It's ready to merge to `dev` if you approve.

Btw, look at the available fields and method in ImmuneSpaceConnection object! So neat and tidy.

```R
> library(ImmuneSpaceR)
> con <- CreateConnection("")
> names(con)
 [1] ".__enclos_env__"       "cache"                 "availableDatasets"     "config"                "study"                
 [6] "plot"                  "mapSampleNames"        "addTreatment"          "getGEMatrix"           "getDataset"           
[11] "getParticipantData"    "listParticipantGroups" "getGEFiles"            "print"                 "clearCache"           
[16] "getGEAnalysis"         "listGEAnalysis"        "listDatasets"          "getGEInputs"           "initialize"           
[21] "listGEMatrices"        "clone"     
```

**Comment by ldash** [comment]
All good with me!

**Pull request merged**
